apiVersion: v1
kind: Service
metadata:
  name: kube2hadoop-svc
  namespace: kube-system
spec:
  selector:
    app: hadoop-token-svc
  ports:
    - protocol: TCP
      port: 9966
      targetPort: 9966