{{- if .Values.conf.certManager.enabled }}
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: {{ include "iddecorator.fullname" . }}-webhook-cert
spec:
  commonName: {{ include "iddecorator.fullname" . }}.{{ .Release.Namespace }}
  dnsNames:
  - {{ include "iddecorator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  - {{ include "iddecorator.fullname" . }}.{{ .Release.Namespace }}.svc
  duration: 2160h0m0s
  issuerRef:
    {{- toYaml .Values.conf.certManager.issuerRef | nindent 4 }}
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  keySize: 2048
  renewBefore: 360h0m0s
  secretName: {{ include "iddecorator.fullname" . }}-cert
  usages:
  - server auth
{{- end }}
