apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iddecorator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  paths.yaml: |
    {{ toYaml .Values.conf.paths | nindent 4 }}