apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iddecorator.fullname" . }}
  labels:
    {{- include "iddecorator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iddecorator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "iddecorator.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.podLabels | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "iddecorator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mutator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
          {{- with .Values.conf.usernameAnnotation -}}
          - --username-annotation-key={{ . }}
          {{- end -}}
          - --log-level={{ .Values.conf.logLevel | default "info" }}
          volumeMounts:
          - mountPath: /etc/webhook/certs
            name: webhook-certs
            readOnly: true
          - mountPath: /etc/config/
            name: config
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ include "iddecorator.fullname" . }}-cert
      - name: config
        configMap:
          name: {{ include "iddecorator.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
