kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "iddecorator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "iddecorator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "iddecorator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
