kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "token-fetcher.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "token-fetcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "token-fetcher.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
