kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "token-fetcher.fullname" . }}-bin
data:
  start_hadoop2kube.sh: |
{{ tuple "bin/_start_hadoop2kube.sh.tpl" . | include "token-fetcher.template" | indent 4 }}
